export interface SeriesSpec {
  seer: string;
  scop: string;
  energyLabelCool: string;
  energyLabelHeat: string;
  noiseIndoor: string;
  wifi: string;
  refrigerant: string;
  features: string[];
  technologies: string[];
  description: string;
}

// Match by checking if description starts with the key
export const SERIES_SPECS: Record<string, SeriesSpec> = {
  // === DAIKIN ===
  "Daikin::Perfera": {
    seer: "9.47",
    scop: "5.20",
    energyLabelCool: "A+++",
    energyLabelHeat: "A+++",
    noiseIndoor: "19 dB(A)",
    wifi: "Standaard (Daikin Onecta app)",
    refrigerant: "R32",
    features: [
      "Flash Streamer luchtzuivering verwijdert allergenen en geuren",
      "Heat Boost: 14% sneller op temperatuur dan vorige generatie",
      "2-zone intelligent eye sensor past luchtrichting automatisch aan",
      "Coanda luchtstroom voor tochtvrijecomfort",
      "Fluisterstil: slechts 19 dB(A) in stille modus",
      "Bediening via smartphone met Daikin Onecta app",
    ],
    technologies: ["Flash Streamer", "Intelligent Eye", "Coanda Effect", "Onecta"],
    description: "De Daikin Perfera is de perfecte oplossing voor een comfortabel klimaat in huis. Met de nieuwste invertertechnologie, luchtzuivering via Flash Streamer en intelligente sensoren die de luchtrichting automatisch aanpassen. Energielabel A+++ voor zowel koelen als verwarmen.",
  },
  "Daikin::Stylish": {
    seer: "8.75",
    scop: "5.15",
    energyLabelCool: "A+++",
    energyLabelHeat: "A++",
    noiseIndoor: "19 dB(A)",
    wifi: "Standaard (Daikin Onecta app)",
    refrigerant: "R32",
    features: [
      "Strak minimalistisch design, slechts 189 mm dik (dunste op de markt)",
      "Grid-Eye 64-zone temperatuursensor voor optimale klimaatregeling",
      "Flash Streamer luchtzuivering",
      "Coanda luchtstroom voor tochtvrijecomfort",
      "Verkrijgbaar in wit, zilver, zwart en zwart hout",
      "Zilver-allergenenfilter tegen fijnstof en allergenen",
    ],
    technologies: ["Flash Streamer", "Grid-Eye Sensor", "Coanda Effect"],
    description: "De Daikin Stylish combineert award-winnend design met geavanceerde technologie. Met slechts 189 mm is het de dunste wandunit op de markt. De Grid-Eye sensor met 64 zones detecteert temperatuurverschillen in de kamer voor optimaal comfort.",
  },
  "Daikin::Emura": {
    seer: "8.75",
    scop: "5.00",
    energyLabelCool: "A+++",
    energyLabelHeat: "A+++",
    noiseIndoor: "19 dB(A)",
    wifi: "Standaard (Daikin Onecta app)",
    refrigerant: "R32",
    features: [
      "Bekroond design met elegante gebogen lijnen",
      "Flash Streamer luchtzuivering tegen virussen en bacteriën",
      "2-zone intelligent eye sensor",
      "Coanda luchtstroom voorkomt tocht",
      "Verkrijgbaar in wit, zilver en zwart",
      "Zilver-allergenenfilter",
    ],
    technologies: ["Flash Streamer", "Intelligent Eye", "Coanda Effect"],
    description: "De Daikin Emura is een premium designmodel dat stijl combineert met krachtige prestaties. Het bekroonde design past in elk interieur, terwijl Flash Streamer technologie de lucht zuivert van allergenen, virussen en geuren.",
  },
  "Daikin::Comfora": {
    seer: "6.92",
    scop: "4.65",
    energyLabelCool: "A++",
    energyLabelHeat: "A+",
    noiseIndoor: "20 dB(A)",
    wifi: "Optioneel (WiFi-adapter apart verkrijgbaar)",
    refrigerant: "R32",
    features: [
      "Uitstekende prijs-kwaliteitverhouding",
      "Econavi sensor voor energiebesparing",
      "Stille werking: 20 dB(A) in stille modus",
      "Compact design",
      "Milieuvriendelijk R32 koudemiddel",
      "Ideaal als instapmodel van Daikin",
    ],
    technologies: ["Econavi"],
    description: "De Daikin Comfora biedt betrouwbare Daikin kwaliteit tegen een aantrekkelijke prijs. Een uitstekend instapmodel met stille werking en energiezuinige prestaties. Perfect voor wie Daikin kwaliteit wil zonder de premium functies.",
  },
  "Daikin::Ururu Sarara": {
    seer: "9.54",
    scop: "5.90",
    energyLabelCool: "A+++",
    energyLabelHeat: "A+++",
    noiseIndoor: "19 dB(A)",
    wifi: "Standaard (Daikin Onecta app)",
    refrigerant: "R32",
    features: [
      "5-in-1: koelen, verwarmen, bevochtigen, ontvochtigen en ventileren",
      "Ururu bevochtiging: voorkomt droge lucht in de winter",
      "Sarara ontvochtigen: comfortabel bij hoge luchtvochtigheid",
      "Ventilatie met warmteterugwinning: verse lucht zonder energieverlies",
      "Flash Streamer luchtzuivering",
      "Hoogste SEER/SCOP op de markt",
    ],
    technologies: ["Ururu (bevochtiging)", "Sarara (ontvochtiging)", "Flash Streamer", "Coanda Effect"],
    description: "De Daikin Ururu Sarara is het absolute topmodel. Als enige airco ter wereld combineert het 5 functies: koelen, verwarmen, bevochtigen, ontvochtigen en ventileren. Met de hoogste energie-efficiëntie op de markt is dit de meest complete klimaatoplossing.",
  },

  // === GREE ===
  "Gree::Fairy": {
    seer: "7.50",
    scop: "4.10",
    energyLabelCool: "A+++",
    energyLabelHeat: "A++",
    noiseIndoor: "19 dB(A)",
    wifi: "Standaard (GREE+ app)",
    refrigerant: "R32",
    features: [
      "Cold Plasma luchtzuivering",
      "7 ventilatorsnelheden voor fijne regeling",
      "Follow Me functie: afstandsbediening meet temperatuur",
      "Slaapstand met automatische temperatuurregeling",
      "Verkrijgbaar in wit, antraciet en zilver",
      "Automatische luchtrichting (3D airflow)",
    ],
    technologies: ["Cold Plasma"],
    description: "De Gree Fairy is een veelzijdig designmodel met Cold Plasma luchtzuivering en 7 ventilatorsnelheden. Het ronde design en de Follow Me functie zorgen voor optimaal comfort in elke ruimte.",
  },
  "Gree::Clivia": {
    seer: "8.50",
    scop: "4.60",
    energyLabelCool: "A+++",
    energyLabelHeat: "A++",
    noiseIndoor: "19 dB(A)",
    wifi: "Standaard (GREE+ app)",
    refrigerant: "R32",
    features: [
      "G-AI kunstmatige intelligentie voor slim klimaatbeheer",
      "UV-C lamp vernietigt bacteriën en virussen",
      "Cold Plasma Plus luchtzuivering",
      "Zelfreinigend filter systeem",
      "Verkrijgbaar in wit, antraciet en zilver",
      "Fluisterstil: slechts 19 dB(A)",
    ],
    technologies: ["G-AI Technology", "Cold Plasma Plus", "UV-C Sterilization"],
    description: "De Gree Clivia is het premium wandmodel van Gree met G-AI kunstmatige intelligentie die leert van uw gebruikspatronen. De UV-C lamp en Cold Plasma Plus zorgen voor schone, gezonde lucht.",
  },
  "Gree::Airy": {
    seer: "8.50",
    scop: "4.60",
    energyLabelCool: "A+++",
    energyLabelHeat: "A++",
    noiseIndoor: "25 dB(A)",
    wifi: "Standaard (GREE+ app)",
    refrigerant: "R32",
    features: [
      "UV-C lamp voor luchtzuivering",
      "Cold Plasma Plus ionisator",
      "Slimme ontvochtiging",
      "3D luchtstroom voor gelijkmatige verdeling",
      "7 ventilatorsnelheden",
      "Verkrijgbaar in wit en zilver",
    ],
    technologies: ["Cold Plasma Plus", "UV-C Sterilization", "AI Control"],
    description: "De Gree Airy combineert modern design met geavanceerde luchtzuivering via UV-C en Cold Plasma Plus technologie. Beschikbaar in wit en zilver voor een stijlvolle toevoeging aan elk interieur.",
  },
  "Gree::Charmo": {
    seer: "7.00",
    scop: "4.00",
    energyLabelCool: "A++",
    energyLabelHeat: "A+",
    noiseIndoor: "37 dB(A)",
    wifi: "Standaard (GREE+ app, Alexa/Google Home)",
    refrigerant: "R32",
    features: [
      "G10 Inverter technologie voor energiebesparing",
      "Compressor-deken voor geluidsreductie buitenunit",
      "Compatibel met Alexa en Google Home",
      "Breed werkbereik: koelt bij 46\u00B0C, verwarmt bij -15\u00B0C",
      "Milieuvriendelijk R32 koudemiddel",
      "Voordelige instapper van Gree",
    ],
    technologies: ["G10 Inverter"],
    description: "De Gree Charmo is een betrouwbaar budgetmodel met G10 Inverter technologie. Compatibel met Alexa en Google Home, en werkt zelfs bij extreme temperaturen van -15\u00B0C tot 46\u00B0C.",
  },

  // === LG ===
  "LG::DUALCOOL Standard Plus": {
    seer: "6.50",
    scop: "4.00",
    energyLabelCool: "A++",
    energyLabelHeat: "A+",
    noiseIndoor: "19 dB(A)",
    wifi: "Standaard (LG ThinQ app)",
    refrigerant: "R32",
    features: [
      "Dual Inverter Compressor met 10 jaar garantie",
      "Auto-reiniging voorkomt schimmelvorming",
      "AI Eco koeling: leert van uw gebruikspatronen",
      "Spraakbesturing via Alexa en Google Assistant",
      "Fluisterstil: slechts 19 dB(A)",
      "Compact en stijlvol design",
    ],
    technologies: ["Dual Inverter Compressor", "ThinQ", "AI Eco"],
    description: "De LG DUALCOOL Standard Plus biedt betrouwbare LG kwaliteit met de befaamde Dual Inverter Compressor en 10 jaar garantie. Slim, zuinig en fluisterstil.",
  },
  "LG::DUALCOOL Premium": {
    seer: "9.50",
    scop: "5.10",
    energyLabelCool: "A+++",
    energyLabelHeat: "A+++",
    noiseIndoor: "19 dB(A)",
    wifi: "Standaard (LG ThinQ app)",
    refrigerant: "R32",
    features: [
      "Dual Inverter Compressor met 10 jaar garantie",
      "UVnano technologie: elimineert 99,99% bacteriën op ventilator",
      "Ionisator voor schonere lucht",
      "Soft Air: indirecte luchtstroom voor extra comfort",
      "AI Auto koeling met slimme sensor",
      "Fluisterstil: slechts 19 dB(A)",
    ],
    technologies: ["Dual Inverter Compressor", "UVnano", "Soft Air", "ThinQ"],
    description: "De LG DUALCOOL Premium is het topmodel met UVnano technologie die 99,99% van de bacteriën op de ventilator elimineert. De Soft Air functie zorgt voor indirecte luchtstroom zonder tocht.",
  },
  "LG::ARTCOOL Gallery": {
    seer: "7.20",
    scop: "4.30",
    energyLabelCool: "A++",
    energyLabelHeat: "A+",
    noiseIndoor: "20 dB(A)",
    wifi: "Standaard (LG ThinQ app)",
    refrigerant: "R32",
    features: [
      '27-inch LCD-scherm: toon uw eigen foto\'s en kunstwerken',
      "Dual Inverter Compressor met 10 jaar garantie",
      "3-weg indirecte luchtstroom",
      "AI Dry functie voor ontvochtiging",
      "Sluimermodus: verborgen luchtuitlaat onderin",
      "Screen mirroring via smartphone",
    ],
    technologies: ["ARTCOOL Gallery LCD", "Dual Inverter Compressor", "AI Dry", "ThinQ"],
    description: "De LG ARTCOOL Gallery is een airco én kunstwerk. Het 27-inch LCD-scherm met houten frame toont uw favoriete foto's of kunstwerken. Wanneer de airco uit staat, ziet het eruit als een ingelijst schilderij.",
  },
  "LG::DUALCOOL Deluxe": {
    seer: "7.60",
    scop: "4.60",
    energyLabelCool: "A++",
    energyLabelHeat: "A++",
    noiseIndoor: "19 dB(A)",
    wifi: "Standaard (LG ThinQ app)",
    refrigerant: "R32",
    features: [
      "Dual Inverter Compressor met 10 jaar garantie",
      "Ionisator voor luchtzuivering",
      "Auto-reiniging voorkomt schimmelvorming",
      "AI koeling past zich aan uw gewoonten aan",
      "Spraakbesturing via Alexa en Google Assistant",
      "Stijlvol design met verborgen display",
    ],
    technologies: ["Dual Inverter Compressor", "Ionizer", "ThinQ"],
    description: "De LG DUALCOOL Deluxe biedt een premium ervaring met ionisator voor luchtzuivering en het kenmerkende strakke design met verborgen display.",
  },
  "LG::DUALCOOL Premium+": {
    seer: "8.50",
    scop: "4.60",
    energyLabelCool: "A+++",
    energyLabelHeat: "A++",
    noiseIndoor: "19 dB(A)",
    wifi: "Standaard (LG ThinQ app)",
    refrigerant: "R32",
    features: [
      "Dual Inverter Compressor met 10 jaar garantie",
      "PM 1.0 sensor detecteert ultrafijnstof",
      "Luchtzuivering en -filtratie",
      "AI Auto koeling",
      "Fluisterstil: slechts 19 dB(A)",
      "Spraakbesturing via Alexa en Google Assistant",
    ],
    technologies: ["Dual Inverter Compressor", "PM 1.0 Sensor", "ThinQ"],
    description: "De LG DUALCOOL Premium+ combineert krachtige koeling met geavanceerde luchtzuivering. De PM 1.0 sensor detecteert ultrafijnstof en activeert automatisch de luchtzuivering.",
  },

  // === MITSUBISHI ELECTRIC ===
  "Mitsubishi Electric::MSZ-AP": {
    seer: "8.60",
    scop: "4.80",
    energyLabelCool: "A+++",
    energyLabelHeat: "A++",
    noiseIndoor: "18 dB(A)",
    wifi: "Standaard (MELCloud app, Alexa/Google Home)",
    refrigerant: "R32",
    features: [
      "Stilste in zijn klasse: slechts 18 dB(A)",
      "Nachtmodus: -3 dB(A) op buitenunit voor buren",
      "Anti-allergeen enzymfilter",
      "Breed capaciteitsbereik van 1,5 tot 7,1 kW",
      "Weekprogramma via timer",
      "Compact design voor elke ruimte",
    ],
    technologies: ["MELCloud", "Night Mode"],
    description: "De Mitsubishi Electric MSZ-AP is de stilste in zijn klasse met slechts 18 dB(A). De nachtmodus verlaagt ook het geluid van de buitenunit, ideaal in woonwijken. Een betrouwbaar en veelzijdig wandmodel.",
  },
  "Mitsubishi Electric::MSZ-EF": {
    seer: "9.10",
    scop: "5.90",
    energyLabelCool: "A+++",
    energyLabelHeat: "A++",
    noiseIndoor: "21 dB(A)",
    wifi: "Standaard (MELCloud app)",
    refrigerant: "R32",
    features: [
      "Bekroond vlak design (Kirigamine Zen)",
      "Plasma Quad filter vangt fijnstof, allergenen en virussen",
      "Nano Platinum filter met antibacteriële werking",
      "Verkrijgbaar in wit, zilver en zwart",
      "R32 koudemiddel voor lagere CO2-uitstoot",
      "Bediening via MELCloud app",
    ],
    technologies: ["Kirigamine Zen", "Plasma Quad", "Nano Platinum Filter", "MELCloud"],
    description: "De Mitsubishi Electric MSZ-EF Kirigamine Zen is een design-icoon met vlakke lijnen en premium afwerking. Het Plasma Quad filtersysteem vangt zelfs de kleinste deeltjes, virussen en allergenen.",
  },
  "Mitsubishi Electric::MSZ-LN": {
    seer: "10.50",
    scop: "5.20",
    energyLabelCool: "A+++",
    energyLabelHeat: "A+++",
    noiseIndoor: "19 dB(A)",
    wifi: "Standaard (MELCloud app)",
    refrigerant: "R32",
    features: [
      "3D i-see sensor met 8 zones detecteert personen en past luchtrichting aan",
      "Plasma Quad Plus: geavanceerd filtersysteem",
      "Dual Barrier Coating beschermt de warmtewisselaar",
      "Nachtmodus voor buitenunit",
      "Verkrijgbaar in Ruby Red, Onyx Black, Pearl White en Natural White",
      "Hoogste SEER rating in de Mitsubishi Electric lijn",
    ],
    technologies: ["3D i-see Sensor", "Plasma Quad Plus", "Dual Barrier Coating", "MELCloud"],
    description: "De Mitsubishi Electric MSZ-LN Diamond is het absolute premium model met de hoogste energie-efficiëntie. De 3D i-see sensor detecteert personen in 8 zones en past de luchtrichting automatisch aan voor maximaal comfort.",
  },

  // === MITSUBISHI HEAVY ===
  "Mitsubishi Heavy::SRK-ZS Premium": {
    seer: "8.50",
    scop: "4.60",
    energyLabelCool: "A+++",
    energyLabelHeat: "A++",
    noiseIndoor: "19 dB(A)",
    wifi: "Standaard (Smart M-Air app)",
    refrigerant: "R32",
    features: [
      "Bewegingssensor schakelt automatisch in/uit",
      "3D Auto luchtstroom voor gelijkmatige verdeling",
      "Italiaans design door Tensa srl, Milaan",
      "Allergeen-vrij filter",
      "Verkrijgbaar in titanium en contrast zwart-wit",
      "WiFi-besturing via Smart M-Air app",
    ],
    technologies: ["3D Auto", "Motion Sensor", "Allergen Clear Filter"],
    description: "De Mitsubishi Heavy SRK-ZS Premium combineert Italiaans design met Japanse technologie. De bewegingssensor detecteert of er iemand in de kamer is en past de werking automatisch aan voor energiebesparing.",
  },
  "Mitsubishi Heavy::SRK-ZSX Diamond": {
    seer: "10.30",
    scop: "5.20",
    energyLabelCool: "A+++",
    energyLabelHeat: "A+++",
    noiseIndoor: "19 dB(A)",
    wifi: "Standaard (Smart M-Air app)",
    refrigerant: "R32",
    features: [
      "Hyper Inverter voor maximale energie-efficiëntie",
      "Bewegingssensor schakelt automatisch in/uit",
      "Dubbele luchtklep met bereik tot 17 meter",
      "Verwijderbaar inlaatpaneel voor eenvoudig onderhoud",
      "CFD-geoptimaliseerde ventilatorbladen",
      "Award-winnend design (Silver A'Design Award 2017)",
    ],
    technologies: ["Hyper Inverter", "Motion Sensor", "Double Supply Air Valve"],
    description: "De Mitsubishi Heavy SRK-ZSX Diamond is het topmodel met Hyper Inverter technologie en de hoogste energie-efficiëntie in de MHI lijn. De dubbele luchtklep blaast geconditioneerde lucht tot 17 meter ver.",
  },
  "Mitsubishi Heavy::SRK-ZR Diamond": {
    seer: "8.10",
    scop: "4.70",
    energyLabelCool: "A++",
    energyLabelHeat: "A++",
    noiseIndoor: "21 dB(A)",
    wifi: "Standaard (Smart M-Air app)",
    refrigerant: "R32",
    features: [
      "Krachtige capaciteit voor grotere ruimtes",
      "Hyper Inverter technologie",
      "3D Auto luchtstroom",
      "Bewegingssensor",
      "R32 koudemiddel",
      "Geschikt voor ruimtes tot 80 m\u00B2",
    ],
    technologies: ["Hyper Inverter", "Motion Sensor", "3D Auto"],
    description: "De Mitsubishi Heavy SRK-ZR Diamond is ontworpen voor grotere ruimtes. Met capaciteiten tot 6,3 kW levert het krachtige koeling en verwarming met Hyper Inverter technologie.",
  },

  // === MITSUI ===
  "Mitsui::CDX Dynamic": {
    seer: "7.20",
    scop: "4.20",
    energyLabelCool: "A++",
    energyLabelHeat: "A+",
    noiseIndoor: "20.5 dB(A)",
    wifi: "Standaard (AC Freedom app)",
    refrigerant: "R32",
    features: [
      "Follow-Me eco-sensor in afstandsbediening",
      "Antibacterieel filter",
      "Plasma-ion luchtzuivering",
      "3D luchtstroom",
      "Auto-herstart na stroomuitval",
      "Stille werking: 20,5 dB(A)",
    ],
    technologies: ["Follow-Me Eco Sensor", "Plasma-Ion"],
    description: "De Mitsui CDX Dynamic biedt uitstekende waarde met Follow-Me technologie die de temperatuur meet bij de afstandsbediening in plaats van bij de wandunit. Inclusief plasma-ion luchtzuivering en WiFi.",
  },
  "Mitsui::MTX Trend": {
    seer: "6.10",
    scop: "4.00",
    energyLabelCool: "A++",
    energyLabelHeat: "A+",
    noiseIndoor: "21 dB(A)",
    wifi: "Optioneel (WiFi-module apart verkrijgbaar)",
    refrigerant: "R32",
    features: [
      "Betaalbare instapper met bewezen technologie",
      "4-weg automatische luchtrichting",
      "Zelfdiagnose systeem",
      "Intelligente ontdooiing",
      "LED-display",
      "R32 milieuvriendelijk koudemiddel",
    ],
    technologies: [],
    description: "De Mitsui MTX Trend is het budgetmodel dat bewezen koeling en verwarming biedt tegen een scherpe prijs. Ideaal als instapmodel voor wie een betrouwbare airco zoekt zonder poespas.",
  },
  "Mitsui::ZDX Dynamic Platinum": {
    seer: "7.20",
    scop: "4.20",
    energyLabelCool: "A++",
    energyLabelHeat: "A+",
    noiseIndoor: "20.5 dB(A)",
    wifi: "Standaard (AC Freedom app)",
    refrigerant: "R32",
    features: [
      "Premium mat zwart design",
      "Follow-Me eco-sensor",
      "Antibacterieel filter",
      "Plasma-ion luchtzuivering",
      "3D luchtstroom",
      "Auto-clean functie",
    ],
    technologies: ["Follow-Me Eco Sensor", "Plasma-Ion"],
    description: "De Mitsui ZDX Dynamic Platinum is het premium model met stijlvol mat zwart design. Dezelfde geavanceerde technologie als de CDX Dynamic, maar dan in een opvallend donker jasje.",
  },
};

export function getSeriesSpec(brand: string, description: string | null): SeriesSpec | null {
  const lijn = (description || "").split("|")[0].trim();
  const key = `${brand}::${lijn}`;
  return SERIES_SPECS[key] || null;
}
